= Teragrep UI

This project contains the user interface for Teragrep. 

== Features

* notebook-based interface
* automatic graph creation based on search results
* data exploring tools
* real-time collaborative script editing
* shareable notebooks
* file importing and exporting
* dataset exporting
* version control

== v1.0.0 Release Runbook

The ajs_01 v1.0.0 release runbook is divided into the following sections:

* Notebook management
* Paragraph execution
* Results reporting
* Collarobative editing
* Errors and notifications
* Persistance
* Jobs management
* Authorization and authentication
* Other

Tests in each section must complete as expected before the release can be published. 

=== Notebook Management

=== Paragraph Execution

=== Results Reporting

=== Collaborative Editing

=== Errors and Notifications

=== Persistence

=== Jobs Management

=== Authorization and Authentication

=== Other 

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to Set-Up 

You can setup the project as it is but it doesn't contain the back-end implementation. If you want to install ajs_01 with Teragrep back-end, see also the instructions in https://github.com/teragrep/zep_01[zep_01] project. 

If you want to include DPL (Data Processing Language) interpreter in your Teragrep installation, see instructions in https://github.com/teragrep/pth_07[pth_07] project.

=== Requirements

TBA

=== Installation

TBA

== Custom Theme

You can customize the color scheme of Teregrep to match your own color palette or brand identity. Read more https://docs.teragrep.com/doc_01/1.0.0/administrator%20guide/custom-theme.html[here].

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/ajs_01/issues/new/choose[opening an issue] or submitting a pull request. 

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories. 

